### ISSUE TITLE
Switching don't work when ping_ip is the same as failover_ip

### ISSUE THREAD

**Issue by riverfall** [mrkamel/heartbeat#2]
Hi,

If I try to set ping_ip is the same as failover_ip, the system doesn't switch between servers.

My config:

```
base_url: https://robot-ws.your-server.de
basic_auth:
  username: [cutted]
  password: [cutted]
failover_ip: 1.2.3.4
ping_ip: 1.2.3.4
ips:
  - ping: 2.3.4.5
    target: 2.3.4.5
  - ping: 3.4.5.6
    target: 3.4.5.6
interval: 30
timeout: 10
tries: 3
```

In this case, log looks like this:

```
I, [2013-11-11T13:59:32.024087 #10269]  INFO -- : 1.2.3.4 is up.
I, [2013-11-11T14:00:04.242432 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:00:07.177245 #10269]  INFO -- : Not responsible for 2.3.4.5
I, [2013-11-11T14:05:09.419816 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:05:09.996530 #10269]  INFO -- : Not responsible for 2.3.4.5.
I, [2013-11-11T14:10:12.214836 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:10:12.932809 #10269]  INFO -- : Not responsible for 2.3.4.5.
I, [2013-11-11T14:15:15.176340 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:15:15.774078 #10269]  INFO -- : Not responsible for 2.3.4.5.
I, [2013-11-11T14:20:17.998591 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:20:23.707318 #10269]  INFO -- : Not responsible for 2.3.4.5.
I, [2013-11-11T14:25:25.928112 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:25:26.511541 #10269]  INFO -- : Not responsible for 2.3.4.5.
I, [2013-11-11T14:30:28.739342 #10269]  INFO -- : 1.2.3.4 is down.
I, [2013-11-11T14:30:31.446149 #10269]  INFO -- : Not responsible for 2.3.4.5.
```

But if I set ping_ip as the first server, switching works after the first packet lost, without tries etc:

```
I, [2013-11-11T15:34:36.178875 #11312]  INFO -- : 2.3.4.5 is up.
I, [2013-11-11T15:34:39.381142 #11312]  INFO -- : 2.3.4.5 is down.
I, [2013-11-11T15:34:42.955294 #11312]  INFO -- : Switching to 3.4.5.6.
```

System: ubuntu server 13.10

Best regards
